spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: http://student-service:9002/
          predicates:
            - Path=/students/**
        - id: department-service
          uri: http://department-service:9001/
          predicates:
             - Path=/departments/**
        - id: course-service
          uri: http://course-service:9003/
          predicates:
             - Path=/courses/**

server:
  port: ${port:9191}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always